# Import libraries

In [1]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
from datasets import load_dataset
import pandas as pd

/Users/fcalado/Desktop/anti-trans-legislation/training/heritage/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Sentiment Analysis

By default, the 🤗 Transformers library text-classification pipeline uses the [distilbert-base-uncased-finetuned-sst-2-english](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english) model. This model is based on a distilled, uncased version of [BERT](https://huggingface.co/bert-base-uncased) that has been fine-tuned on the [Stanford Sentiment Treebank 2](https://huggingface.co/datasets/sst2) (SST-2) dataset. The SST-2 dataset is a binary classification dataset for training models to learn the sentiment of words, phrases, and sentences. It contains 215,154 unique manually labeled texts of varying lengths. The model card describes SST-2:

> The corpus is based on the dataset introduced by Pang and Lee (2005) and consists of 11,855 single sentences extracted from movie reviews. It was parsed with the Stanford parser and includes a total of 215,154 unique phrases from those parse trees, each annotated by 3 human judges.

In [15]:
# Sentiment Analysis
classifier = pipeline("text-classification", model="SamLowe/roberta-base-go_emotions")

Device set to use mps:0

In [16]:
# Define a task function
def classify_sentiment(prompt):
        output = classifier(prompt)
        return output

In [ ]:
# Pass a prompt into the task function
classify_sentiment(ds['train']['text'][10])

[{'label': 'neutral', 'score': 0.6804832816123962}]

In [19]:
for i in ds['train']['text'][:10]:
    print(i)
    print(classify_sentiment(i))

The weaponization of the U.S. Department of Justice against purported enemies of the Biden-Harris administration is nothing new.
[{'label': 'neutral', 'score': 0.7223581671714783}]
The Department’s persecution of pro-life advocates, praying grandmothers, and fathers of young children under the Freedom of Access to Clinic Entrances Act (while routinely ignoring arson and vandalism at crisis pregnancy centers chargeable under the same law) is hard to deny.
[{'label': 'neutral', 'score': 0.7027313113212585}]
But the Department’s meritless criminal prosecution of Dr. Eithan Haim, a whistleblowing physician who exposed covert gender medicine procedures inflicted on minors at Texas Children’s Hospital—performed in violation of state law—is an outrageous abuse of its law enforcement authority.
[{'label': 'annoyance', 'score': 0.43028414249420166}]
The principal wrongdoer in Dr. Haim’s case—leading the charge in his criminal prosecution for alleged violation of the Health Insurance Portability and Accountability Act (“HIPAA”)—is Assistant United States Attorney Tina Ansari, a Democratic donor who targeted Haim in part during a time when her law license had been suspended by the Texas Bar for failure to pay her bar dues.
[{'label': 'neutral', 'score': 0.9375830292701721}]
As legal scholar Ed Whelan has correctly pointed out, the only reason Haim was targeted was because “he ran afoul of the transgender ideology that dominates” the current presidential administration.
[{'label': 'neutral', 'score': 0.6419640779495239}]
But now, in pleadings filed by Dr. Haim’s lawyers and in separate complaints filed by a former DOJ lawyer with both the State Bar of Texas and the Justice Department’s Office of Professional Responsibility, Ansari is accused of having “knowingly sponsored false information” to the federal grand jury that indicted Haim and of having “knowingly misled a tribunal and presented deliberately misleading information to a grand jury.”
[{'label': 'neutral', 'score': 0.7463356256484985}]
In other words, she wasn’t just practicing law on a suspended license.
[{'label': 'neutral', 'score': 0.8684070706367493}]
She is charged with lying to the grand jury to get Haim indicted—itself a violation of federal law.
[{'label': 'neutral', 'score': 0.7529940009117126}]
As journalist Christopher Rufo reported, Dr. Haim knew the hospital “secretly continued to perform transgender medical interventions, including the use of implantable puberty blockers, on minor children” after it assured the public it was no longer engaging in such medically dangerous and risky actions.
[{'label': 'neutral', 'score': 0.9339284896850586}]
Haim did not disclose the name of any patients, or any personally identifiable medical information protected by federal law under HIPAA (42 U.S.C. §§1320d-6).
[{'label': 'neutral', 'score': 0.9443564414978027}]

## Question Answering

The Question Answering pipeline has two required parameters: 

* `question` The question being asked
* `context` The source material that should be used to answer this question

In [25]:
# Question Answering
reader = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use mps:0

In [26]:
# Define a task function
def answer_question(question, context):
    output = reader(question=question, context=context)
    return pd.DataFrame([output])

In [45]:
# grab the first 50 sentences as "context"

input_sentences = ds['train']['text'][:50]
context = ''.join(input_sentences)

In [ ]:
# Pass the prompt into the task function

question = "what's going on?"
answer = answer_question(question, context)

In [49]:
# it returns a dataframe

answer

      score  start  end                                             answer
0  0.029369    128  178  The Department’s persecution of pro-life advoc...

In [47]:
answer['answer'][0]

'The Department’s persecution of pro-life advocates'

## Summarization

The `clean_up_tokenization_spaces` parameter removes extraneous spaces created through the detokenization process. If tokenization breaks up a string into separate tokens, then detokenization joins together a series of tokens into a string.

In [2]:
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")
pipe = pipeline("summarization", model="facebook/bart-large-cnn")

Device set to use mps:0

In [3]:
df = pd.read_json('cleaned.json', lines=True)
df.head()

,title,author,date,url,takeaways,text
0,Biden-Harris DOJ Prosecutor Targets Trans Whis...,"[Hans A. von Spakovsky, Sarah Parshall Perry]",2024-11-07,https://www.heritage.org/courts/commentary/bid...,[The weaponization of the U.S. Department of J...,The weaponization of the U.S. Department of Ju...
1,Wisconsin Public Schools’ Gender Policies Shut...,"[Thomas Jipping, Sarah Parshall Perry]",2024-10-23,https://www.heritage.org/gender/commentary/wis...,[Schools are generally in charge of matters su...,The Supreme Court has said that parents’ right...
2,United States v. Skrmetti: Oral Arguments Indi...,[Sarah Parshall Perry],2024-12-13,https://www.heritage.org/gender/commentary/uni...,[Tennessee is one of 26 states that have enact...,"On Wednesday, December 3, the U.S. Supreme Cou..."
3,Trump’s Transgender Orders Are Well Within Exe...,"[Paul J. Larkin, Sarah Parshall Perry]",2025-02-19,https://www.heritage.org/gender/commentary/tru...,[They claim the president’s directive prohibit...,"In two short weeks, President Donald Trump has..."
4,Follow the Law,[Sarah Parshall Perry],2025-02-27,https://www.heritage.org/gender/commentary/fol...,[Hurson’s decision halts the directives of Pre...,It’s difficult to envision a more dizzying exe...

In [4]:
df['text'][0]

'The weaponization of the U.S. Department of Justice against purported enemies of the Biden-Harris administration is nothing new. The Department’s persecution of pro-life advocates, praying grandmothers, and fathers of young children under the Freedom of Access to Clinic Entrances Act (while routinely ignoring arson and vandalism at crisis pregnancy centers chargeable under the same law) is hard to deny. But the Department’s meritless criminal prosecution of Dr. Eithan Haim, a whistleblowing physician who exposed covert gender medicine procedures inflicted on minors at Texas Children’s Hospital—performed in violation of state law—is an outrageous abuse of its law enforcement authority. The principal wrongdoer in Dr. Haim’s case—leading the charge in his criminal prosecution for alleged violation of the Health Insurance Portability and Accountability Act (“HIPAA”)—is Assistant United States Attorney Tina Ansari, a Democratic donor who targeted Haim in part during a time when her law license had been suspended by the Texas Bar for failure to pay her bar dues. As legal scholar Ed Whelan has correctly\xa0pointed\xa0out, the only reason Haim was targeted was because “he ran afoul of the transgender ideology that dominates” the current presidential administration. But now, in\xa0pleadings\xa0filed by Dr. Haim’s lawyers and in separate complaints filed by a former DOJ lawyer with both the State Bar of Texas and the Justice Department’s Office of Professional Responsibility, Ansari is accused of having “knowingly sponsored false information” to the federal grand jury that indicted Haim and of having “knowingly misled a tribunal and presented deliberately misleading information to a grand jury.” In other words, she wasn’t just practicing law on a suspended license. She is charged with lying to the grand jury to get Haim indicted—itself a violation of federal law. As journalist Christopher Rufo\xa0reported, Dr. Haim knew the hospital “secretly continued to perform transgender medical interventions, including the use of implantable puberty blockers, on minor children” after it assured the public it was no longer engaging in such medically dangerous and risky actions. Haim did not disclose the name of any patients, or any personally identifiable medical information protected by federal law under HIPAA (42 U.S.C. §§1320d-6). The Justice Department didn’t care. It charged Haim with criminally violating HIPAA anyway, arguing that he had disclosed “individually identifiable health information,” something explicitly prohibited by HIPAA. The punishment for such a conviction? Up to 10 years in prison and a $250,000 fine. The original grand jury indictment claimed he had obtained HIPAA-protected patient medical information through “false pretenses.” Haim had, allegedly, accessed the medical records after he completed his surgical rotation at Texas Children’s Hospital in January 2021 and had no more patients there. But, according to the ethics complaints and a motion for grand jury material filed by Haim’s lawyers, Haim did still have patients at the hospital, and Ansari and other government prosecutors knew it. That would have made his access of patient records entirely legal under HIPAA. The hospital provided records to the government showing that Haim continued to treat patients at the hospital after his residency was over, during the time when the grand jury indictment claims he wasn’t treating any patients and had no legal right to access patient records. All of this is also apparent in a “Superseding Indictment” Ansari filed on Oct. 10 that, as the defense points out, deletes all references to Haim accessing patient records when he was supposedly no longer treating patients at the hospital. Yet the new indictment still claims he obtained those records under “false pretenses.” As a result, Haim’s lawyers asked the court to provide them with access to all of the materials the grand jury considered when it issued the original indictment. Why? Because the documents would likely show that the hospital told Ansari that Haim was continuing to treat patients at the hospital when she was making presentations to the grand jury claiming the opposite. Grand jury materials are secret under\xa0applicable\xa0federal rules of criminal procedure. But the grand jury materials should be released in this case, says Haim’s lawyers, under the exceptions provided in the rules, to determine if the government “knowingly” sponsored “false information before the grand jury” and if that false information was “capable” of “influencing the grand jury’s decision.” The lawyers are right when they tell the court that if “the government has made material misleading statements to the grand jury, the defense should be permitted to review the relevant grand jury material.” Haim has also filed a “Show Cause” motion asking the court to issue an order against Ansari for “engaging in the practice of law with a suspended law license.” The motion says she was administratively suspended on Sept. 1 for not paying her bar dues. She responded that she remedied this problem as of Sept. 19. But as Haim’s attorneys point out, Ansari was signing and filing pleadings in the case during her suspension, which violates the Texas Code of Professional Conduct, the court’s own rules, and the internal rules of the Justice Department that direct DOJ lawyers to immediately cease their representation of the government during such a lapse. Not surprisingly, Ansari is a big donor to Democrat candidates, having contributed a total of $11,350, which is quite a bit of money for a career civil service employee. Mind you, there is nothing illegal about those donations, but as the complaint filed against her with the Office of Professional Responsibility at DOJ states, it raises serious questions on whether “her specific ideological or political view as it related to the highly controversial issues in this prosecution” biased her judgment and prompted her to mislead a federal grand jury. The pursuit of Dr. Haim is simply outrageous. As one of Haim’s principal lawyers, Marcella Burke, told us, “DOJ has charged Dr. Haim with a non-existent crime. At a charitable minimum, this is a reckless prosecution and at its extreme, it is malicious prosecution.” The fact that the indictment hasn’t been dropped indicates what’s really going on here. Because Haim didn’t release any personal medical information about any patient, something HIPAA prevents, the new indictment now charges him with allegedly acting to “cause malicious harm” to the hospital and its physicians. And what is the “malicious harm” Haim caused? Apparently, the Justice Department believes that he inflicted “malicious harm” by letting the public know that a children’s hospital was lying when it claimed it was no longer inflicting transgender medical abuse on its minor patients and that the hospital was violating Texas law. That is a prosecution based on politics and ideology, not the law and the interests of justice or, for that matter, of the public at large. While the prosecution continues against Dr. Haim, Texas Attorney General Ken Paxton has\xa0launched\xa0an investigation into Texas Children’s Hospital for performing gender “affirming” medicine in violation of state law. The Lonestar State has outlawed hormone replacement therapy for minors and other forms of “gender-affirming care,” if that type of mistreatment can be called “care.” AG Paxton has\xa0warned\xa0that “doctors who continue to provide these harmful ‘gender transition’ drugs and treatments will be prosecuted to the full extent of the law.” If his claim is true, Dr. Haim should be praised for exposing wrongdoing at Texas Children’s Hospital. Instead, he faces a federal criminal indictment. Sadly, the U.S. Justice Department’s view of law enforcement now appears to be driven by politics, not justice.'

In [5]:
# Define a task function
def summarize(text):
    outputs = pipe(text, max_length=150, clean_up_tokenization_spaces=True)
    return outputs[0]['summary_text']

In [6]:
# Pass the prompt into the task function
summarize(df['text'][0])

'Dr. Eithan Haim exposed covert gender medicine procedures at Texas Children’s Hospital. Haim knew the hospital “secretly continued to perform transgender medical interventions, including the use of implantable puberty blockers, on minor children” Haim did not disclose the name of any patients, or any personally identifiable medical information protected by federal law.'

In [10]:
for i in df['text'][47:89]:
    summary = summarize(i)
    summaries.append(summary)

RuntimeError: MPS backend out of memory (MPS allocated: 17.46 GB, other allocations: 23.11 MB, max allowed: 18.13 GB). Tried to allocate 1.25 GB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

In [12]:
len(summaries)

47

In [21]:
summarize(df['text'][2])

'The U.S. Supreme Court heard oral arguments in one of the term’s marquee cases: United States v. Skrmetti. At issue is the constitutionality of a Tennessee law, SB1 (codified at\xa0Tenn. Code Ann. § 68-33-103(a)(1), which prohibits any medical procedure for the purpose of “Enabling a minor to identify with, or live as, a purported identity inconsistent with the minor’S sex”'

In [22]:
summarize(df['text'][3])

'President Donald Trump has issued scores of executive orders related to gender identity. Julian Zelizer: Critics claim that he lacks the authority to do so. He says Congress can legislate through appropriations laws but only “as long as it does so clearly” Zelizer says the president’s executive order does not violate any specific law.'

In [27]:
import torch
import gc

# Clear all caches
torch.mps.empty_cache()
gc.collect()

# Restart your kernel/notebook

8008